# Site settings
title: 'A Head Full of Wishes'
subtitle: 'News, reviews and articles'
email: andy@fullofwishes.co.uk
description: >
  A Head Full of Wishes is a site for Galaxie 500, Luna, Damon & Naomi, Dean & Britta and Dean Wareham.
  With news, articles and lists of releases and past and future shows. 
podcast-description: >
  A Head full of Wishes is a site for fans of Galaxie 500, Luna, Damon & Naomi, Dean & Britta and Dean Wareham. The podcast is as much about being a fan as it is about the music.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.fullofwishes.co.uk" # the base hostname & protocol for your site
image: http://media.fullofwishes.co.uk/00-misc/ahfow-web/ahfow-site-image.jpg
twitter_username: ahfow
github_username:  grange85
permalink: /:year/:month/:day/:title/
jekyll-archives:
  enabled: ['month','categories']
  layouts:
    month: month-archive
    category: category-archive
  permalinks:
    month: '/:year/:month/'
    category: '/category/:name/'

paginate: 10
excerpt_separator: <!--more-->

# Build settings
port: 4040
markdown: kramdown
source: /media/xander4/DATA/07-AHFOW-WWW/
destination: /home/andy/sites/www.fullofwishes.co.uk/
exclude: [
    '_notes',
    'Gemfile',
    'Gemfile.lock'
  ]
gems: [
        bootstrap-sass,
        jekyll-archives,
        jekyll-paginate,
        jekyll-sitemap
        ]
