#  Site settings
title: 'A Head Full of Wishes'
subtitle: 'Galaxie 500, Luna, Damon & Naomi, Dean & Britta &hellip;'
email: andy@fullofwishes.co.uk
baseurl:
url: https://www.fullofwishes.co.uk
domain: https://www.fullofwishes.co.uk
description: >
  A Head Full of Wishes is a site for Galaxie 500, Luna, Damon & Naomi, Dean & Britta and Dean Wareham.
  With news, articles and lists of releases and past and future shows.
podcast-description: >
  A Head full of Wishes is a site for fans of Galaxie 500, Luna, Damon & Naomi, Dean & Britta and Dean Wareham. The podcast is as much about being a fan as it is about the music.
image: https://media.fullofwishes.co.uk/00-misc/ahfow-web/ahfow-site-image.jpg
ahfow-version: '3.0'
github_comments_repository: grange85/ahfow-www-comments

sass:
  sass_dir: _sass
  style: compressed

collections: 
  articles:
    output: true
    permalink: /:collection/:name/
  share:
    output: true
    permalink: /:collection/:name/

twitter_username: ahfow
github_username:  grange85
permalink: /:year/:month/:day/:title/

jekyll-archives:
  enabled: ['month','categories','tags']
  layouts:
    month: month-archive
    category: category-archive
    tag: tag-archive
  permalinks:
    month: '/:year/:month/'
    category: '/category/:name/'
    tag: '/tag/:name/'

pagination: 
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 9
  permalink: '/page:num/'
  title: ':title - page :num'
  limit: 10
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  trail: 
    before: 2
    after: 2
  extension: html
  indexpage: 'index'

excerpt_separator: <!--more-->

jekyll_compose:
  auto_open: true
  default_front_matter:
    drafts:
      layout: post
      sitemap: true
      series-title: 
      github_comments_issueid: 
      author: 
        display_name: Andy
        login: admin
        email: andy@grange85.co.uk
        url: https://www.grange85.co.uk
      imageurl:
      categories:
       - 
      tags: 
       - 
    posts:
      layout: post
      sitemap: true
      series-title: 
      github_comments_issueid: 
      author:
        display_name: Andy
        login: admin
        email: andy@grange85.co.uk
        url: https://www.grange85.co.uk
      imageurl: 
      categories:
       - 
      tags:
       - 
# Build settings
livereload: false
host: 0.0.0.0
port: 4040
markdown: kramdown
environment: production
future: false

# default excludes
exclude:
- _notes
- Rakefile
- .git
- config
- _deploy/
- _archived-posts/
- _templates/
- .jekyll-cache
- "*.swp"
- "*.swo"
- "*.swn"


plugins: [
      ]
