#  Site settings
title: 'A Head Full of Wishes'
subtitle: 'Galaxie 500, Luna, Damon & Naomi, Dean & Britta &hellip;'
author: Andy Aldridge
email: andy@fullofwishes.co.uk
baseurl:
url: https://www.fullofwishes.co.uk
domain: https://www.fullofwishes.co.uk
description: >
  A Head Full of Wishes is a site for Galaxie 500, Luna, Damon & Naomi, Dean & Britta and Dean Wareham.
  With news, articles and lists of releases and past and future shows.
podcast-description: >
  A Head full of Wishes is a site for fans of Galaxie 500, Luna, Damon & Naomi, Dean & Britta and Dean Wareham. The podcast is as much about being a fan as it is about the music.
image: https://media.fullofwishes.co.uk/00-misc/ahfow-web/ahfow-site-image.jpg
ahfow_version: '4.0'
github_comments_repository: grange85/ahfow-www-comments

main_categories:
  - news
  - admin
  - editorial
  - galaxie 500
  - luna
  - damon & naomi
  - dean & britta
  - dean wareham
  - my record collection
  - 13 most beautiful
  - artefacts
  - originals
  - pictures
  - video
  - velvet underground tour diary
  - lost tracks

collections: 
  articles:
    output: true
    permalink: /:collection/:name/
  share:
    output: true
    permalink: /:collection/:name/

twitter_username: ahfow
github_username:  grange85
permalink: /:year/:month/:day/:title/
plausible_domain: "fullofwishes.co.uk"
goat_counter: fullofwishes

theme: no-style-please
theme_config:
  appearance: "dark"
  back_home_text: "<-- back to home"
  date_format: "%Y-%m-%d"
  show_description: true
favicon: "favicon-32x32.png"
jekyll_compose:
  auto_open: true
  default_front_matter:
    drafts:
      layout: post
      sitemap: true
      series-title: 
      github-comments-issueid: 
      author: 
        display_name: Andy
        login: admin
        email: andy@grange85.co.uk
        url: https://www.grange85.co.uk
      image:
      categories:
       - 
      tags: 
       - 
    posts:
      layout: post
      sitemap: true
      series-title: 
      github-comments-issueid: 
      author:
        display_name: Andy
        login: admin
        email: andy@grange85.co.uk
        url: https://www.grange85.co.uk
      image: 
      categories:
       - 
      tags:
       - 
# Build settings
livereload: false
host: 0.0.0.0
port: 4040
markdown: kramdown
environment: production
future: false

# default excludes
exclude:
- vendor
- _notes
- Rakefile
- .git
- config
- _deploy/
- _site
- _archived-posts/
- _templates/
- .jekyll-cache
- "*.swp"
- "*.swo"
- "*.swn"


plugins:
  - jekyll-feed
  - jekyll-seo-tag
