# Site settings
title: 'A Head Full of Wishes'
subtitle: 'News, reviews and articles'
email: andy@fullofwishes.co.uk
baseurl:
url: https://www.fullofwishes.co.uk
domain: https://www.fullofwishes.co.uk
description: >
  A Head Full of Wishes is a site for Galaxie 500, Luna, Damon & Naomi, Dean & Britta and Dean Wareham.
  With news, articles and lists of releases and past and future shows.
podcast-description: >
  A Head full of Wishes is a site for fans of Galaxie 500, Luna, Damon & Naomi, Dean & Britta and Dean Wareham. The podcast is as much about being a fan as it is about the music.
image: https://media.fullofwishes.co.uk/00-misc/ahfow-web/ahfow-site-image.jpg

twitter_username: ahfow
github_username:  grange85
permalink: /:year/:month/:day/:title/
jekyll-archives:
  enabled: ['month','categories']
  layouts:
    month: month-archive
    category: category-archive
  permalinks:
    month: '/:year/:month/'
    category: '/category/:name/'

paginate: 10
excerpt_separator: <!--more-->

# Build settings
port: 4040
markdown: kramdown
environment: production
version: 5.0.2
exclude: [
    '_notes',
    'Gemfile',
    'Gemfile.lock',
    '.sass-cache',
    '.git'
  ]
plugins: [
        bootstrap-sass,
        jekyll-archives,
        jekyll-paginate
        ]
