name: Deploy A Head Full of Wishes

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'manual deploy'
      deploy-environment:
        type: choice
        description: Environment
        required: true
        options:
        - development
        - production
  push:
    branches:
      - main
      deploy-environment: production
  schedule:
    # Schedule to post every day
    - cron: '37 6 * * *'

jobs:
  deployment:
    runs-on: ubuntu-20.04
    environment:
      name: ${{ github.event.inputs.deploy-environment }}
      url: https://www.fullofwishes.co.uk
    steps:
    - uses: actions/checkout@v3

    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1 # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    # Standard usage
    - name: Build site
      run: |
        bundle exec jekyll build --config _config.yml,_config_build.yml

    # Example deployment: Push to S3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Create minified json for search
      run: |
        python3 -c 'import json, sys;json.dump(json.load(sys.stdin), sys.stdout)' < _deploy/search.json > _deploy/search-min.json

    - name: Sync output to S3
      run: |
        aws s3 sync --size-only --exclude '.sass-cache' _deploy s3://www.fullofwishes.co.uk
        aws s3 mv --content-type "text/xml" --metadata-directive REPLACE s3://www.fullofwishes.co.uk/feed.xml s3://www.fullofwishes.co.uk/feed
        aws cloudfront create-invalidation --no-cli-pager --distribution-id ${{ secrets.FULLOFWISHES_WWW_DISTRIBUTION_ID }} --paths "/*"
        aws cloudfront create-invalidation --no-cli-pager --distribution-id ${{ secrets.FULLOFWISHES_CDN_DISTRIBUTION_ID }} --paths "/*"
